FROM cypress/browsers:latest
RUN apt-get update -y &&apt-get install -y python3
ENV PATH /home/root/.local/bin:${PATH}
WORKDIR /app
COPY requirements.txt .
COPY . .
RUN apt-get install -y python3-pip && pip install -r requirements.txt --break-system-packages
