FROM cypress/browser:latest
RUN apt-get install python 3 -y
COPY requirements.txt .
ENV PATH /home/root/.local/bin:${PATH}
RUN apt-get update && apt-get install -y python3-pip && pip install -r requirements.txt
COPY . .
CMD python -m pipescrape
