FROM cypress/browsers:latest
RUN apt-get update -y &&apt-get install -y python3
ENV PATH=/home/root/.local/bin:${PATH}
WORKDIR /app
RUN mkdir /app/downlaods
COPY requirements.txt /app
COPY ./pipescrape/ /app/pipescrape
RUN apt-get install -y python3-pip && pip install --no-cache-dir -r requirements.txt --break-system-packages
CMD python -m pipescrape
